name: 'Secret scanning'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  scan:
    name: Scan secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.95.5
        with:
          extra_args: --results=verified,unknown --json
